### ISSUE TITLE
Incompatability with Sodium, Animatica, & Enhanced Block Entities

### ISSUE THREAD

**Issue by KingJayan** [bewisclient-team/Bewisclient#121]
As seen in this reddit, I troubleshooted: https://www.reddit.com/r/fabricmc/comments/1h59bdd/could_not_execute_entrypoint_stage_client_due_to/

When I launched Fabric MC 1.21.1 with Bewis + sodium animatica & EBE, it crashed. Removed Animatica & EBE, still crash as seen in reddit post.

**Comment by Bewis09** [comment]
So I usually play with sodium and for me it works, but let me see if I can do something about your issue

**Comment by Bewis09** [comment]
Ok so I looked at your crash report and It looks like it is a problem with the mixin for the block outline. I can do something about, but I will not release a new version for 1.21.1, but It will be fixed with the 1.21.4 version
